<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ogrenciListe.aspx.cs" Inherits="ogrenciListe" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="style.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <h1 class="baslik">ÖĞRENCİ LİSTELE </h1><br />
      
        <asp:Label ID="Labelfakulte" runat="server" Text="Fakülte:" CssClass="textboxLabel" ></asp:Label> 
        <asp:DropDownList ID="DropDownListfklt" CssClass="btn btn-default dropdown-toggle dropdowlist " runat="server" AutoPostBack="true" AppendDataBoundItems="true" OnSelectedIndexChanged="DropDownListfklt_SelectedIndexChanged">
           <asp:ListItem Value="0" Text="Seçiniz."></asp:ListItem>      
        </asp:DropDownList> 

        <asp:Label ID="Labelbolum" runat="server" Text="Bölüm:" CssClass="textboxLabel"></asp:Label > 
        <asp:DropDownList ID="DropDownListblm" CssClass="btn btn-default dropdown-toggle dropdowlist " runat="server" AutoPostBack="true" AppendDataBoundItems="true" >
          <asp:ListItem Value="0" Text="Seçiniz."></asp:ListItem>  
        </asp:DropDownList>

        <asp:Label ID="Labelsinif" runat="server" Text="Sınıf:" CssClass="textboxLabel"></asp:Label >    
        <asp:DropDownList ID="DropDownListsnf" CssClass="btn btn-default dropdown-toggle dropdowlist " runat="server" AutoPostBack="true" AppendDataBoundItems="true" >
          <asp:ListItem Value="0" Text="Seçiniz."></asp:ListItem>
        </asp:DropDownList> 

        <asp:Button ID="Buttonliste" OnClick="Buttonliste_Click" CssClass="btn btn-success buton"  runat="server" Text="LİSTELE" /> 

         <asp:Button ID="Buttontmliste" OnClick="Buttontmliste_Click" CssClass="btn btn-success buton"  runat="server" Text="TÜMÜNÜ LİSTELE" /> 

        <asp:Button ID="Buttonanasayfa" OnClick="Buttonanasayfa_Click" CssClass="btn btn-danger buton" runat="server" Text="ANASAYFA" />  <br /><br /><br />

        <asp:GridView ID="GridView1" CssClass="table table-hover Grid" runat="server"  AutoGenerateDeleteButton="true" OnRowDeleting="GridView1_RowDeleting" DataKeyNames="ÖĞRENCİ NO"></asp:GridView><br />
        
        <asp:Button ID="Buttondok" OnClick="Buttondok_Click" CssClass="btn btn-success buton"  runat="server" Text="EXCEL'E AKTAR" />
    </div>
    </form>
</body>
</html>
