<%@ Page Language="C#" AutoEventWireup="true" CodeFile="ogrenciNotEkle.aspx.cs" Inherits="ogrenciNotEkle" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="style.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <h1 class="baslik">ÖĞRENCİ NOT EKLE </h1><br />

        <asp:Label ID="Labelogrno" runat="server" Text="Öğrenci Numarası:" CssClass="textboxLabel" ></asp:Label>
        <asp:DropDownList ID="DropDownListogrno" class="btn btn-default dropdown-toggle dropdowlist" runat="server" AutoPostBack="true" AppendDataBoundItems="true" OnSelectedIndexChanged="DropDownListogrno_SelectedIndexChanged" >
               <asp:ListItem Value="0" Text="Seçiniz."></asp:ListItem>
        </asp:DropDownList>
    
        <asp:Label ID="Labeldrsad" runat="server" Text="Ders Ad:" CssClass="textboxLabel" ></asp:Label>
        <asp:DropDownList ID="DropDownListdrsad" CssClass="btn btn-default dropdown-toggle dropdowlist" runat="server" AppendDataBoundItems="true">
                <asp:ListItem Value="0" Text="Seçiniz."></asp:ListItem>
        </asp:DropDownList> 

        <asp:Label ID="Labelnot" runat="server" Text="Not:" CssClass="textboxLabel" ></asp:Label>
        <asp:TextBox ID="TextBoxnot" CssClass="form-inline textbox"  runat="server"  placeholder="Not Giriniz..." ></asp:TextBox>

        <asp:Button ID="Buttonekle" OnClick="Buttonekle_Click" CssClass="btn btn-success buton" runat="server" Text="KAYDET" />

        <asp:Button ID="Buttonanasayfa" OnClick="Buttonanasayfa_Click" CssClass="btn btn-danger buton" runat="server" Text="ANASAYFA" />&emsp; <br /><br /><br />

        <asp:GridView ID="GridViewnot" CssClass="table table-hover Grid" runat="server" OnDataBound="GridViewnot_DataBound" RowHeaderColumn="harfnıtı" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" OnRowDeleting="GridViewnot_RowDeleting" DataKeyNames="id">
            <Columns>
                <asp:BoundField DataField="id" HeaderText="Id" />
                <asp:BoundField DataField="ogrencino" HeaderText="ÖĞRENCİ NO" />               
                <asp:BoundField DataField="adsoyad" HeaderText="AD SOYAD" />
                 <asp:BoundField DataField="dersad" HeaderText="DERS" />
                 <asp:BoundField DataField="ogrencinotu" HeaderText="NOT" />
                <asp:TemplateField HeaderText="HARF NOTU">
                     <ItemTemplate>
                         <asp:Label ID="Label1" runat="server" ></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView><br />
        
        <asp:Button ID="Buttonaktar" OnClick="Buttonaktar_Click" CssClass="btn btn-success buton" runat="server" Text="EXCEL'E AKTAR" />
    </div>
    </form>
</body>
</html>
